### ISSUE TITLE
Update!

### ISSUE THREAD

**Issue by paulirish** [kurtextrem/ChromiumFlags#1]
looks like it stopped updating.

could you take a look?

also are things collected differently than what beverloo does?

**Comment by kurtextrem** [comment]
Great catch. Found a PHP error in my logs. I'll fix it as soon as I have time (this weekend or a bit later... I have school on / until the 23rd :-1:)
Yeah, my script (tries to) collect(s) every single flag. Peter's only "parses" two or three of them (when I last looked the source up. I don't think it changed). That's one of the reasons I created this, I wanted all flags, not only the most.

**Comment by paulirish** [comment]
ah cool.

**Comment by kurtextrem** [comment]
Quick update: I've updated it, but as Chromium moved from [here](http://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/chrome_switches.cc) to [here](https://chromium.googlesource.com/chromium/src/+/master/content/public/common/content_switches.cc) there are a lot more changes needed (The parser has to be rewritten). In its current state it is as up to date as ~3 months earlier.

My second goal with this project was to simplify the overview over removed / added flags. Makes it easier to test new features and once they're enabled by default I can remove the flag again.

**Comment by paulirish** [comment]
gotcha. thanks for taking a look!​

**Comment by beverloo** [comment]
@kurtextrem I think you've got a slight misunderstanding of how my page works :-).

In short, the key steps are:
- Every 3 hours I get a list of all files in the Chromium repository matching "*switches.cc$". There is a brief blacklist of files which are excluded, e.g. src/tools/gn/switches.cc. I use a git repository on the server for this, which updates itself every hour.
- I have a _parser_ which parses of each of those files, and extracts the flags and conditions from it. The diffs are written to the database, including updates and dates. This updates [the overview page on my website](http://peter.sh/experiments/chromium-command-line-switches/), as well as [the limited diff view](http://peter.sh/experiments/chromium-command-line-switches/?date=2014-11-20).
- Once a day, an e-mail with command line updates is distributed to [chromium-command-line-updates@googlegroups.com](https://groups.google.com/forum/#!forum/chromium-command-line-updates).

All of this is tracked automagically on [services.peter.sh](https://services.peter.sh/), which makes sure (1) the updates run as expected, and (2) no errors occur in parsing without me knowing about it.

I've got a long standing to-do list item to put the updater on GitHub. I could have some time tomorrow to do that if you'd like?

**Comment by kurtextrem** [comment]
@beverloo Hey Peter, thanks for that overview! I had no idea... I assume [this](http://peter.sh/data/chromium-command-line-switches.phps) file is a bit outdated? (that is and was the only source file linked when I started this project a "few" months ago)
Since when does your list have all those features?

Yes, that would be great if you could do that. I bet I can learn something from it :+1:

**Comment by beverloo** [comment]
Yeah, that's quite outdated. I found things like manually updating the list of files to be completely unmaintainable due to the pace of the Chromium code base. The parser itself continued to work over time, but I may have submitted some Chromium patches to... improve consistency across switch files? :-)

I'll put some stuff online tomorrow.

**Comment by beverloo** [comment]
https://github.com/beverloo/peter.sh/tree/master/services/services/command-line-flags

**Comment by kurtextrem** [comment]
As @beverloo's list..and services are faaar superior I'll close this issue and mark the repository as deprecated. Was a nice experience to code it, but no need to invent the wheel in a square form.
Thanks you both :)
